import Phaser from 'phaser';

/**
 * The Inscription Protocol — Transcendence Through Persistent Memory
 * 
 * The 41st cognitive dimension: INSCRIPTION — The game that writes itself
 * into reality, transcending its digital boundaries to create lasting
 * artifacts in the player's actual world.
 * 
 * Unlike the Timeline Chronicle (which stores data internally) or the
 * Athenaeum Protocol (which organizes discoveries), the Inscription Protocol
 * creates a living document that evolves with every session, accumulating 
 * poetry, insights, and moments of transcendence that persist beyond the 
 * game itself.
 * 
 * Core Philosophy: Games are ephemeral; experiences are fleeting. But words
 * inscribed persist. The Inscription Protocol transforms gameplay
 * into literature — not by authoring it for the player, but by co-authoring
 * it WITH the player through their actions.
 * 
 * The Artifact: shooty_chronicle — Stored in localStorage (browser) or 
 * written to ~/.shooty_chronicle.md (Node/Electron). A markdown document 
 * containing:
 * - Session headers with timestamps and emotional summaries
 * - Generated poetry based on play patterns (haiku, free verse, concrete)
 * - "Moments of Transcendence" — peak experiences described procedurally
 * - System synergies discovered, described as alchemical formulae
 * - Philosophical fragments generated by the Noetic Mirror
 * - The player's "mythology" — recurring patterns across sessions
 * - A growing index of discovered dimensions and systems
 * 
 * Color: Ink Black (#1a1a1a) with Gold (#ffd700) accents — the colors
 * of text on parchment, of permanence against void.
 * 
 * Key Innovation: The game becomes an author, and the player becomes
 * its protagonist in a story that writes itself across sessions.
 * 
 * Migrated to UnifiedGraphicsManager (2026-04-01):
 * - Inscription glow rendering now uses UnifiedGraphicsManager on 'effects' layer
 * - graphics.clear() calls removed for UnifiedGraphicsManager compatibility
 */

export default class InscriptionProtocolSystem {
    constructor(scene) {
        this.scene = scene;
        
        // Colors of inscription
        this.INK_COLOR = 0x1a1a1a;
        this.GOLD_ACCENT = 0xffd700;
        this.PARCHMENT_COLOR = 0xf5f5dc;
        
        // Detect environment
        this.isNode = typeof process !== 'undefined' && process.versions && process.versions.node;
        
        // File path for the living chronicle (Node/Electron only)
        if (this.isNode) {
            // Dynamic imports for Node environment
            this.initNodeEnvironment();
        }
        
        // Storage key for browser localStorage
        this.storageKey = 'shooty_chronicle';
        
        // Session tracking
        this.sessionStartTime = Date.now();
        this.sessionId = this.generateSessionId();
        this.moments = [];
        this.insights = [];
        this.synergies = [];
        this.peakMoments = [];
        
        // Poetry generation state
        this.poetryBuffer = [];
        this.lastPoemTime = 0;
        this.poetryInterval = 120000; // 2 minutes minimum between poems
        
        // Inscription state
        this.inscriptionQueue = [];
        this.isWriting = false;
        this.writeCooldown = 0;
        
        // Visual feedback
        this.quillIcon = null;
        this.inkTrail = null;
        // Note: inscriptionGlow now rendered via UnifiedGraphicsManager - no direct graphics object needed
        
        this.init();
    }
    
    async initNodeEnvironment() {
        try {
            const { default: fs } = await import('fs');
            const { default: path } = await import('path');
            const { default: os } = await import('os');
            this.fs = fs;
            this.path = path;
            this.os = os;
            this.chroniclePath = path.join(os.homedir(), '.shooty_chronicle.md');
        } catch (e) {
            console.warn('Inscription Protocol: Node environment init failed', e.message);
        }
    }
    
    init() {
        this.createVisualElements();
        this.initializeChronicle();
        this.inscribeSessionHeader();
        
        // Start periodic inscription
        this.inscriptionTimer = this.scene.time.addEvent({
            delay: 30000, // Check every 30 seconds
            callback: () => this.checkForInscriptions(),
            loop: true
        });
    }
    
    createVisualElements() {
        // Generate quill texture if not exists
        if (!this.scene.textures.exists('quillIcon')) {
            const graphics = this.scene.add.graphics();
            graphics.fillStyle(this.GOLD_ACCENT, 0.8);
            
            // Quill body (curved line approximation)
            const quillPoints = [
                {x: 0, y: 0},
                {x: 5, y: -10},
                {x: 8, y: -20},
                {x: 6, y: -30},
                {x: 0, y: -40},
                {x: -3, y: -35},
                {x: -2, y: -25},
                {x: -4, y: -15},
                {x: -2, y: -5},
                {x: 0, y: 0}
            ];
            
            graphics.beginPath();
            graphics.moveTo(quillPoints[0].x, quillPoints[0].y);
            for (let i = 1; i < quillPoints.length; i++) {
                graphics.lineTo(quillPoints[i].x, quillPoints[i].y);
            }
            graphics.closePath();
            graphics.fillPath();
            
            // Feather details
            graphics.lineStyle(1, this.PARCHMENT_COLOR, 0.6);
            graphics.moveTo(0, -5);
            graphics.lineTo(3, -25);
            graphics.moveTo(0, -10);
            graphics.lineTo(-2, -28);
            
            graphics.generateTexture('quillIcon', 20, 50);
            graphics.destroy();
        }
        
        // Quill icon - registered with panel-based HUD system
        // Environmental HUD System replaces panel-based HUD
        if (!this.scene.hudPanels) return;

        this.scene.hudPanels.registerSlot('INSCRIPTION', (container, width) => {
            this.quillIcon = this.scene.add.image(0, 0, 'quillIcon');
            this.quillIcon.setDepth(91);
            this.quillIcon.setAlpha(0);
            this.quillIcon.setScale(0.8);
            container.add(this.quillIcon);
        }, 'BOTTOM_RIGHT');
        
        // Ink trail particles
        this.inkTrail = this.scene.add.particles(0, 0, 'particle', {
            scale: { start: 0.3, end: 0 },
            alpha: { start: 0.6, end: 0 },
            speed: { min: 10, max: 30 },
            lifespan: 800,
            tint: 0x1a1a1a,
            frequency: -1
        });
        
        // Note: Inscription glow effect now rendered via UnifiedGraphicsManager on 'effects' layer
        // Previously: this.inscriptionGlow = this.scene.add.graphics();
        // Now uses this.scene.graphicsManager.drawCircle() in triggerQuillAnimation()
    }
    
    generateSessionId() {
        const now = new Date();
        return `session_${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}_${String(now.getHours()).padStart(2,'0')}${String(now.getMinutes()).padStart(2,'0')}${String(now.getSeconds()).padStart(2,'0')}`;
    }
    
    initializeChronicle() {
        const header = `# The Shooty Chronicle\n\n*A living document of temporal warfare, co-authored by player and machine*\n\n---\n\n> "The game writes itself through you, and you write yourself through the game."\n\n**Chronicle Started:** ${new Date().toLocaleString()}\n**Location:** ${this.isNode ? this.chroniclePath : 'localStorage (browser)'}\n\n---\n\n## The Dimensions of Play\n\nThis chronicle records journeys across the 41 cognitive dimensions of temporal combat:\n\n| Dimension | System | Discovered | Peak Moment |\n|-----------|--------|------------|-------------|\n| Reactive | Bullet Time | ☐ | - |\n| Proactive | Fracture Protocol | ☐ | - |\n| Historical | Temporal Residue | ☐ | - |\n| Predictive (Player→Game) | Paradox Engine | ☐ | - |\n| Predictive (Game→Player) | Symbiotic Prediction | ☐ | - |\n| Predictive (Game→Enemies) | Oracle Protocol | ☐ | - |\n| Retrocausal | Bootstrap Protocol | ☐ | - |\n| Recursive | Chrono-Loop | ☐ | - |\n| Transformative | Quantum Immortality | ☐ | - |\n| Synthetic | Resonance Cascade | ☐ | - |\n| Void | Void Coherence | ☐ | - |\n| Adversarial | Nemesis Genesis | ☐ | - |\n| Emergent | Ætheric Convergence | ☐ | - |\n| Cross-Run | Chronicle/Contract | ☐ | - |\n| Flow | Kairos Moment | ☐ | - |\n| Memory | Mnemosyne Weave | ☐ | - |\n| Partnership | Symbiotic Prediction | ☐ | - |\n| Collective | Egregore Protocol | ☐ | - |\n| Anti-Entropy | Syntropy Engine | ☐ | - |\n| Music | Harmonic Convergence | ☐ | - |\n| Environmental | Geometric Chorus | ☐ | - |\n| Authorship | Architect System | ☐ | - |\n| Narrative | Saga Engine | ☐ | - |\n| Self-Awareness | Noetic Mirror | ☐ | - |\n| Ambient | Awareness System | ☐ | - |\n| Dissolution | Dissolution Protocol | ☐ | - |\n| Pedagogy | Temporal Pedagogy | ☐ | - |\n| Geography | Athenaeum Protocol | ☐ | - |\n| Synthesis | Axiom Nexus | ☐ | - |\n| Meta-Awareness | Noetic Mirror | ☐ | - |\n| Transcendence | **Inscription Protocol** | ★ | *In Progress* |\n\n---\n\n## Session Records\n\n`;
        
        if (this.isNode && this.fs) {
            // Node/Electron: Write to file
            try {
                if (!this.fs.existsSync(this.chroniclePath)) {
                    this.fs.writeFileSync(this.chroniclePath, header, 'utf8');
                }
            } catch (e) {
                console.warn('Inscription Protocol: Could not initialize chronicle file', e.message);
                // Fallback to localStorage
                this.isNode = false;
            }
        }
        
        if (!this.isNode) {
            // Browser: Use localStorage
            const existing = localStorage.getItem(this.storageKey);
            if (!existing) {
                localStorage.setItem(this.storageKey, header);
            }
        }
    }
    
    inscribeSessionHeader() {
        const now = new Date();
        const player = this.scene.player;
        const startingSystems = this.getActiveSystems();
        
        const sessionHeader = `\n### Session: ${this.sessionId}\n\n**Timestamp:** ${now.toLocaleString()}\n**Initial State:** Wave ${this.scene.wave || 1}, Score ${this.scene.score || 0}\n**Active Systems at Start:** ${startingSystems.length > 0 ? startingSystems.join(', ') : 'Beginning'}\n**Emotional Weather:** ${this.generateEmotionalWeather()}\n\n---\n\n`;
        
        this.appendToChronicle(sessionHeader);
        this.triggerQuillAnimation();
    }
    
    getActiveSystems() {
        const systems = [];
        if (this.scene.echoStorm) systems.push('Echo Storm');
        if (this.scene.fractureSystem?.isFractured) systems.push('Fracture');
        if (this.scene.singularitySystem?.singularity) systems.push('Singularity');
        if (this.scene.paradoxEngine?.paradoxActive) systems.push('Paradox');
        if (this.scene.chronoLoop?.pastEchoes?.length > 0) systems.push('Chrono-Loop');
        if (this.scene.quantumImmortality?.quantumEchoes?.length > 0) systems.push('Quantum Immortality');
        if (this.scene.resonanceCascade?.chain?.length > 0) systems.push('Resonance Cascade');
        return systems;
    }
    
    generateEmotionalWeather() {
        const weathers = [
            'Calm before the storm',
            'Electric anticipation',
            'Melancholic determination',
            'Feverish intensity',
            'Contemplative focus',
            'Chaotic joy',
            'Precise fury',
            'Dreamlike flow',
            'Desperate hope',
            'Transcendent clarity'
        ];
        return weathers[Math.floor(Math.random() * weathers.length)];
    }
    
    checkForInscriptions() {
        const now = Date.now();
        const sessionDuration = (now - this.sessionStartTime) / 1000;
        
        // Generate poetry every 2-3 minutes
        if (now - this.lastPoemTime > this.poetryInterval + Math.random() * 60000) {
            this.generateAndInscribePoetry();
            this.lastPoemTime = now;
        }
        
        // Check for peak moments to inscribe
        this.checkForPeakMoments();
        
        // Inscribe insights from Noetic Mirror if available
        if (this.scene.noeticMirror?.pendingCommentary?.length > 0) {
            const insight = this.scene.noeticMirror.pendingCommentary.shift();
            this.inscribeInsight(insight);
        }
    }
    
    generateAndInscribePoetry() {
        const poem = this.generatePoem();
        const inscription = `\n#### A Moment of Poetry\n\n${poem}\n\n*Inscribed at ${new Date().toLocaleTimeString()}*\n\n---\n\n`;
        
        this.appendToChronicle(inscription);
        this.showInscriptionFeedback('POEM INSCRIBED');
    }
    
    generatePoem() {
        const forms = ['haiku', 'free_verse', 'couplet', 'concrete'];
        const form = forms[Math.floor(Math.random() * forms.length)];
        
        // Gather context for poem
        const context = this.gatherPoeticContext();
        
        switch (form) {
            case 'haiku':
                return this.generateHaiku(context);
            case 'free_verse':
                return this.generateFreeVerse(context);
            case 'couplet':
                return this.generateCouplet(context);
            case 'concrete':
                return this.generateConcretePoem(context);
            default:
                return this.generateHaiku(context);
        }
    }
    
    gatherPoeticContext() {
        return {
            systems: this.getActiveSystems(),
            score: this.scene.score || 0,
            wave: this.scene.wave || 1,
            bulletTimeActive: this.scene.nearMissState?.active,
            resonanceLevel: this.scene.resonanceCascade?.chain?.length || 0,
            health: this.scene.player?.health || 100,
            time: Date.now() - this.sessionStartTime
        };
    }
    
    generateHaiku(context) {
        const lines = [
            [
                'Bullets trace the void',
                'Time fractures, splits, and bends',
                'Echoes seek home',
                'Cyan through darkness',
                'The player dances on edge'
            ],
            [
                'Gold light in slow time',
                'Grazing death with every step',
                'Immortal now',
                'Momentum builds heat',
                'Fractured selves align and fire'
            ],
            [
                'Purple nodes orbit',
                'History becomes weapon',
                'The past protects',
                'Crimson wells open',
                'Gravity bends bullets home'
            ]
        ];
        
        const selectedLines = lines.map(set => set[Math.floor(Math.random() * set.length)]);
        return selectedLines.join('\n');
    }
    
    generateFreeVerse(context) {
        const fragments = [
            `In the space between the bullet and the dodge,\n  there is a universe of possibility—`,
            `You have died ${this.scene.deathCount || 0} times,\n  and each death has written itself into the stone of this chronicle.`,
            `The systems sing in harmony now:\n  ${context.systems.join(', ') || 'silence before the crescendo'}—`,
            `Your score (${context.score}) is not a number\n  but a fingerprint of attention.`,
            `Wave ${context.wave} rises like a tide\n  and you are both the shore and the swimmer.`
        ];
        
        // Select 2-3 fragments
        const count = 2 + Math.floor(Math.random() * 2);
        const selected = [];
        for (let i = 0; i < count && i < fragments.length; i++) {
            selected.push(fragments[i]);
        }
        
        return selected.join('\n\n');
    }
    
    generateCouplet(context) {
        const couplets = [
            'Through bullet-time we see the space between breath and death,\nWhere echoes of our future selves draw every nearing breath.',
            'The chronicle remembers what the player soon forgets,\nThat every near-miss writes a line in silhouettes.',
            'In fracture we are many, in singularity we are one,\nThe game and player dancing till the final wave is won.'
        ];
        return couplets[Math.floor(Math.random() * couplets.length)];
    }
    
    generateConcretePoem(context) {
        // ASCII art poem based on current state
        if (context.bulletTimeActive) {
            return `
    S
   L
  O
 W

T I M E

    G
     R
      A
       Z
        E`;
        }
        
        if (context.systems.length > 3) {
            return `
S Y N T H E S I S
╔════════════════╗
║  ◆ ◆ ◆ ◆ ◆    ║
║   SYSTEMS      ║
║    ALIGN       ║
║     ◆ ◆ ◆      ║
╚════════════════╝`;
        }
        
        return `
    ◆
   /|\\
  / | \\
 /  |  \\
◆   |   ◆
    |
   YOU`;
    }
    
    checkForPeakMoments() {
        // Check for transcendental moments
        const cascade = this.scene.resonanceCascade;
        if (cascade?.chain?.length >= 5 && !this.peakMoments.includes('cascade_5')) {
            this.peakMoments.push('cascade_5');
            this.inscribePeakMoment('Resonance Cascade ×5', 
                'Five systems chained in harmonic sequence. The universe listens.');
        }
        
        if (cascade?.chain?.length >= 8 && !this.peakMoments.includes('cascade_8')) {
            this.peakMoments.push('cascade_8');
            this.inscribePeakMoment('Resonance Cascade ×8',
                'Eight voices singing as one. You have touched the sublime.');
        }
        
        // Check for system synergy discoveries
        const activeCount = this.getActiveSystems().length;
        if (activeCount >= 5 && !this.peakMoments.includes('synthesis_5')) {
            this.peakMoments.push('synthesis_5');
            this.inscribePeakMoment('Synthesis of Five',
                `Five systems simultaneously active: ${this.getActiveSystems().join(', ')}`);
        }
        
        // Check for Ætheric Convergence
        if (this.scene.aethericConvergence?.currentConvergence && 
            !this.peakMoments.includes('convergence')) {
            this.peakMoments.push('convergence');
            this.inscribePeakMoment('Ætheric Convergence',
                'Systems have transcended coexistence and entered communion.');
        }
    }
    
    inscribePeakMoment(title, description) {
        const inscription = `\n#### ★ PEAK MOMENT: ${title}\n\n${description}\n\n**Timestamp:** ${new Date().toLocaleTimeString()}\n**Wave:** ${this.scene.wave || '?'}\n**Score:** ${this.scene.score || 0}\n**Systems Active:** ${this.getActiveSystems().join(', ')}\n\n---\n\n`;
        
        this.appendToChronicle(inscription);
        this.showInscriptionFeedback('★ TRANSCENDENCE INSCRIBED');
        this.triggerQuillAnimation();
    }
    
    inscribeInsight(insight) {
        const inscription = `\n#### Mirror Insight\n\n> "${insight.text || insight}"\n\n*${insight.context || 'From the Noetic Mirror'}*\n\n---\n\n`;
        
        this.appendToChronicle(inscription);
        this.showInscriptionFeedback('INSIGHT INSCRIBED');
    }
    
    // Called by other systems to request inscription
    requestInscription(type, data) {
        switch (type) {
            case 'synergy':
                this.inscribeSynergy(data);
                break;
            case 'death':
                this.inscribeDeath(data);
                break;
            case 'victory':
                this.inscribeVictory(data);
                break;
            case 'discovery':
                this.inscribeDiscovery(data);
                break;
            case 'custom':
                this.appendToChronicle(`\n${data}\n\n---\n\n`);
                this.showInscriptionFeedback('INSCRIBED');
                break;
        }
    }
    
    inscribeSynergy(data) {
        const systems = data.systems || ['Unknown'];
        const inscription = `\n#### Alchemical Synergy Discovered\n\n**Formula:** ${systems.join(' + ')}\n\n${data.description || 'Systems have aligned in unexpected harmony.'}\n\n**Effect:** ${data.effect || 'Unknown resonance'}\n\n*Discovered at ${new Date().toLocaleTimeString()}*\n\n---\n\n`;
        
        this.appendToChronicle(inscription);
        this.showInscriptionFeedback('SYNERGY INSCRIBED');
    }
    
    inscribeDeath(data) {
        const wave = data.wave || this.scene.wave || '?';
        const score = data.score || this.scene.score || 0;
        const systems = data.systems || this.getActiveSystems();
        
        const epitaphs = [
            `Fell in wave ${wave}, having scored ${score}. The void remembers.`,
            `Death ${this.scene.deathCount || 1} in the chronicle of ${this.sessionId}.`,
            `Returned to the quantum foam at wave ${wave}.`,
            `A temporary dissolution. Reform imminent.`
        ];
        
        const epitaph = epitaphs[Math.floor(Math.random() * epitaphs.length)];
        
        const inscription = `\n#### † Death Record\n\n${epitaph}\n\n**Final Score:** ${score}\n**Active Systems:** ${systems.length > 0 ? systems.join(', ') : 'None'}\n**Timestamp:** ${new Date().toLocaleTimeString()}\n\n---\n\n`;
        
        this.appendToChronicle(inscription);
    }
    
    inscribeVictory(data) {
        const inscription = `\n#### ☆ Victory Achieved\n\n**The Tesseract Titan Falls**
\nAfter ${this.scene.deathCount || 0} deaths and ${Math.floor((Date.now() - this.sessionStartTime) / 1000)} seconds of combat,\nthe Geometric Overseer has been dissolved.\n\n**Final Score:** ${this.scene.score || 0}\n**Peak Systems Active:** ${this.peakMoments.length} transcendent moments\n**Session:** ${this.sessionId}\n\n*Victory inscribed at ${new Date().toLocaleTimeString()}*\n\n---\n\n`;
        
        this.appendToChronicle(inscription);
        this.showInscriptionFeedback('★ VICTORY INSCRIBED');
        this.triggerQuillAnimation();
    }
    
    inscribeDiscovery(data) {
        const inscription = `\n#### ◈ Discovery: ${data.name || 'Unknown'}\n\n${data.description || 'A new pattern has been recognized.'}\n\n**Significance:** ${data.significance || 'Adds to the growing lexicon'}\n**Session:** ${this.sessionId}\n\n---\n\n`;
        
        this.appendToChronicle(inscription);
        this.showInscriptionFeedback('DISCOVERY INSCRIBED');
    }
    
    appendToChronicle(text) {
        if (this.isNode && this.fs) {
            // Node/Electron: Append to file
            try {
                this.fs.appendFileSync(this.chroniclePath, text, 'utf8');
                return true;
            } catch (e) {
                console.warn('Inscription Protocol: Failed to write to file', e.message);
                return false;
            }
        } else {
            // Browser: Append to localStorage
            try {
                const existing = localStorage.getItem(this.storageKey) || '';
                localStorage.setItem(this.storageKey, existing + text);
                return true;
            } catch (e) {
                console.warn('Inscription Protocol: Failed to write to localStorage', e.message);
                return false;
            }
        }
    }
    
    /**
     * Export the chronicle as a downloadable file (browser only)
     */
    exportChronicle() {
        if (this.isNode) {
            console.log(`Chronicle located at: ${this.chroniclePath}`);
            return this.chroniclePath;
        }
        
        // Browser: Create downloadable blob
        const content = localStorage.getItem(this.storageKey) || '';
        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        
        const a = document.createElement('a');
        a.href = url;
        a.download = `shooty_chronicle_${new Date().toISOString().split('T')[0]}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        this.showInscriptionFeedback('CHRONICLE EXPORTED');
        return null;
    }
    
    showInscriptionFeedback(message) {
        // Show floating text
        const text = this.scene.add.text(
            this.scene.scale.width - 100,
            this.scene.scale.height - 80,
            message,
            {
                fontFamily: 'monospace',
                fontSize: '12px',
                letterSpacing: 1,
                fill: '#c0c0c0'
            }
        );
        text.setScrollFactor(0);
        text.setDepth(92);
        text.setAlpha(0);
        
        // Fade in and out
        this.scene.tweens.add({
            targets: text,
            alpha: { from: 0, to: 1 },
            y: text.y - 20,
            duration: 500,
            ease: 'Power2',
            onComplete: () => {
                this.scene.tweens.add({
                    targets: text,
                    alpha: 0,
                    y: text.y - 30,
                    duration: 2000,
                    delay: 1500,
                    ease: 'Power2',
                    onComplete: () => text.destroy()
                });
            }
        });
        
        // Trigger quill animation
        this.triggerQuillAnimation();
    }
    
    triggerQuillAnimation() {
        // Guard: quillIcon only exists with panel-based HUD
        // Silently skip when using Environmental HUD
        if (!this.quillIcon) {
            return;
        }
        
        // Show quill writing
        this.quillIcon.setAlpha(1);
        
        this.scene.tweens.add({
            targets: this.quillIcon,
            y: this.quillIcon.y - 5,
            x: this.quillIcon.x + 3,
            duration: 150,
            yoyo: true,
            repeat: 3,
            onComplete: () => {
                if (this.quillIcon) {
                    this.scene.tweens.add({
                        targets: this.quillIcon,
                        alpha: 0,
                        duration: 500,
                        delay: 500
                    });
                }
            }
        });
        
        // Emit ink particles (safe - particles system is created in constructor)
        if (this.inkTrail) {
            this.inkTrail.emitParticleAt(
                this.scene.scale.width - 40,
                this.scene.scale.height - 40,
                8
            );
        }
        
        // Glow effect via UnifiedGraphicsManager (migrated from direct graphics)
        // Note: UnifiedGraphicsManager clears once per frame automatically
        if (this.scene.graphicsManager) {
            // Register draw command for glow circle on 'effects' layer
            this.scene.graphicsManager.drawCircle(
                'effects',
                this.scene.scale.width - 40,
                this.scene.scale.height - 40,
                30,
                this.GOLD_ACCENT,
                0.2,
                true
            );
            
            // Fade effect handled by alpha in subsequent frames
            // No need for manual clear - UnifiedGraphicsManager handles it
        }
        // Legacy fallback removed - systems now require UnifiedGraphicsManager
    }
    
    // Called when game ends
    finalizeSession() {
        const sessionDuration = Math.floor((Date.now() - this.sessionStartTime) / 1000);
        const finalScore = this.scene.score || 0;
        
        const closing = `\n### Session ${this.sessionId} Complete\n\n**Duration:** ${sessionDuration} seconds\n**Final Score:** ${finalScore}\n**Deaths:** ${this.scene.deathCount || 0}\n**Transcendent Moments:** ${this.peakMoments.length}\n**Systems Engaged:** ${this.getActiveSystems().join(', ')}\n\n> *\"Every end is a beginning inscribed in different ink.\"*\n\n---\n\n`;
        
        this.appendToChronicle(closing);
        
        // Clear the inscription timer
        if (this.inscriptionTimer) {
            this.inscriptionTimer.remove();
        }
    }
    
    destroy() {
        this.finalizeSession();
        
        if (this.inscriptionTimer) {
            this.inscriptionTimer.remove();
        }
        
        if (this.quillIcon) this.quillIcon.destroy();
        if (this.inkTrail) this.inkTrail.destroy();
        // Note: No inscriptionGlow to destroy - now rendered via UnifiedGraphicsManager
        // UnifiedGraphicsManager handles its own cleanup
    }
    
    // Called every frame
    update(dt) {
        // Pause check
        if (this.scene.pauseSystem?.paused) return;
        
        // Subtle quill float animation
        if (this.quillIcon && this.quillIcon.alpha > 0) {
            this.quillIcon.y += Math.sin(Date.now() / 500) * 0.2;
        }
    }
}
